export const FETCH_PRODUCT= 'FETCH_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATA_PRODUCT = 'UPDATA_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';